version: '3'

services:
  php:
    build: ./php
    container_name: web
    volumes:
      - ../leichttraktor:/var/www/leichttraktor
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
