version: '3'

services:
  web:
    container_name: web
    build: ./web
    ports:
      - 80:80
    privileged: true
    volumes:
      - ../leopard:/var/www/leopard
      - ./web/php.ini:/usr/local/etc/php/php.ini
    
